name: Daily Idea Browser Capture

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:    # Allow manual triggering too

jobs:
  capture:
    runs-on: ubuntu-22.04
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright  # Standard cache location

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Explicit version for better caching
          cache: 'npm'       # Automatic npm caching

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci --prefer-offline  # Uses cached modules when possible

      - name: Install Playwright (conditional)
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps
          npx playwright install-deps  # Only executes on cache miss

      - name: Verify Playwright
        run: npx playwright --version  # Quick sanity check

      - name: Run capture script
        env:
          TARGET_URL: https://ideabrowser.com
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npx ts-node src/index.ts