name: Daily Idea Browser Capture

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:    # Allow manual triggering too

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libwoff1 \
            libvpx9 \
            libevent-2.1-7 \
            libopus0 \
            libavif16 \
            libsecret-1-0 \
            libharfbuzz-icu0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libGLESv2-2 \
            libx264-163 \
            libgstallocators-1.0-0 \
            libgstapp-1.0-0 \
            libgstpbutils-1.0-0 \
            libgstaudio-1.0-0 \
            libgsttag-1.0-0 \
            libgstvideo-1.0-0 \
            libgstgl-1.0-0 \
            libgstcodecparsers-1.0-0 \
            libgstfft-1.0-0 \
            flite1 \
            libflite1 \
            libflite-alsa \
            libflite-cmu-grapheme-lex \
            libflite-cmu-indic-lex \
            libflite-cmu-time-awb \
            libflite-cmu-us-awb \
            libflite-cmu-us-kal \
            libflite-cmu-us-rms \
            libflite-cmu-us-slt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run capture script
        env:
          TARGET_URL: https://ideabrowser.com
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npx ts-node src/index.ts
